# Generated by Django 4.0.6 on 2023-10-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='art',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tag', to='articles.article'),
        ),
        migrations.RemoveField(
            model_name='scope',
            name='tag',
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.tag'),
        ),
    ]
