# Generated by Django 4.0.6 on 2023-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_tag_tag_name_remove_scope_art_scope_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
