# Generated by Django 4.0.6 on 2023-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_tag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=0, verbose_name='Основной'),
        ),
    ]
