# Generated by Django 4.0.6 on 2023-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='id_sens',
            field=models.IntegerField(default=1),
        ),
    ]
