# Generated by Django 4.0.6 on 2023-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensor_description_alter_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id_sens',
            field=models.IntegerField(default=1, verbose_name='номер датчика'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.FloatField(verbose_name='температура'),
        ),
    ]
