# Generated by Django 4.0.6 on 2023-05-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AddField(
            model_name='phone',
            name='custom_id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
